version: '3.8'
volumes:
    postgres_data:
    static:
services:
    db:
        image: postgres:12.0
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    web:
        build: ./
        image: today_weather:latest
        depends_on:
            - db
        volumes:
            - static:/app/docs/static
        expose:
            - 8000
        env_file:
            - ./.env
    nginx:
        build: ./nginx
        image: nginx:1.19.2
        depends_on:
            - web
        volumes:
            - static:/app/docs/static
        ports:
            - ${PORT}:80
    docs:
        build: ./docs
        image: docs:latest
        depends_on:
            - web
        volumes:
            - static:/app/docs/static