version: '3.8'
volumes:
    postgres_data:
    static_data:
services:
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    web:
        build: .
        image: today_weather:latest
        volumes:
            - static_data:/app/today_weather/docs/
        expose:
            - 8080
        depends_on:
            - db
        env_file:
            - ./.env
    nginx:
        build: ./nginx
        ports:
            - 8080:80
        depends_on:
            - web
        volumes:
            - static_data:/app/today_weather/docs/