version: '3.8'
volumes:
    postgres_data:
services:
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    web:
        build: ./
        image: today_weather:latest
        volumes:
            - ./today_weather/docs/:/app/today_weather/docs/
        expose:
            - 80
        depends_on:
            - db
        env_file:
            - ./.env
    nginx:
        build: ./nginx
        image: nginx:latest
        ports:
            - ${PORT}:80
        depends_on:
            - web
        volumes:
            - ./today_weather/docs/:/app/today_weather/docs/