version: '3.8'
volumes:
    postgres_data:
services:
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    web:
        build: .
        image: today_weather:latest
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db
        env_file:
            - ./.env
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web