openapi: 3.0.2
info:
  title: 'Backend API for TodayWeather'
  version: ''

servers:
  - url: today-weather-api.arseniypopov.com

tags:
  - name: localities
    description: ''
  - name: forecast


paths:
  /localities/{locality_id}:
    parameters:
      - name: locality_id
        in: path
        required: true
        description: ''
        schema:
          type: number
    get:
      tags:
        - localities
      summary: Get locality by id.
      responses:
        '200':
          description: Locality returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Locality'
              examples:
                localityExample:
                  $ref: '#/components/examples/localityExample'
        '404':
          description: Locality not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /localities:
    get:
      tags:
        - localities
      summary: Get all localities.
      responses:
        '200':
          description: List of localities returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Locality'
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - forecast
      summary: Supply free-form address input.
      requestBody:
        description: Free-from address input.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: free-from address input
      responses:
        '200':
          description: Forecast for a known locality returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalityForecast'
        '201':
          description: Forecast for a newly added locality returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalityForecast'
        '400':
          description: The supplied address is either too general or too narrow.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /localities/{locality_id}/forecast:
    parameters:
      - name: locality_id
        in: path
        required: true
        description: ''
        schema:
          type: number
    get:
      tags:
        - forecast
      summary: Get forecast for locality.
      responses:
        '200':
          description: Forecast returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalityForecast'
        '404':
          description: Locality not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Locality:
      title: Locality
      type: object
      description: Locality.
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              description: link to the locality object
        name:
          type: string
        lat:
          type: number
        lng:
          type: number
    LocalityForecast:
      title: LocalityForecast
      description: Weather forecast and locality.
      type: object
      properties:
        locality:
          $ref: '#/components/schemas/Locality'
        forecast:
          $ref: '#/components/schemas/Forecast'
    Forecast:
      title: Forecast
      type: object
      description: Weather forecast.
      properties:
        temp_min:
          type: number
        temp_max:
          type: number
        rain:
          type: boolean
        snow:
          type: boolean
    Error:
      title: Error
      type: object
      description: Error description.
      properties:
        error:
          type: string
          description: error message
  examples:
    localityExample:
      value:
        {
        "locality": {
          "lat": 55.755826,
          "links": {
              "self": "/localities/1"
          },
          "lng": 37.6172999,
          "name": "Moscow, Russia"
        }
        }